### ISSUE TITLE
Prevaluation --> reduces time for slurm and transfer

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshop#52] opened 2024-11-01 15:32 UTC
**[edit: text edit by Richel] Currently, we have a good schedule. However, we wanted to experiment with a prevaluation which is estimated to take 10 minutes. Where are we going to steal those 10 minutes from?**

What to do?
5 min reduction each or 10 minutes in one?
Present durations:

Transferring files: 70 m
Slurm: 70

**Comment by richelbilderbeek** [comment] 2024-11-02 09:48
@bclaremar I don't know/remember what the problem is with the schedule and I am happy with how it currently is. 

If needed, sure, reduce the time on Slurm (I've split it up in three sessions, as can be seen already in the schedule) and I adapt by teaching less (and prepare less, quite convenient for me) :-) .

**Comment by bclaremar** [comment] 2024-11-06 21:13
Well, I was counting on that 10 extra minutes from introduction will be required for the prevaluation.
Shortened the efficient jobs session with 10 minutes but it can be flexible I guess

**Comment by richelbilderbeek** [comment] 2024-11-07 06:05
I offered to have 10 minutes off of my session, go ahead and do :+1: . For the file transfer, ask Pavlin. I do predict, he is flexible there too :+1:

**Comment by richelbilderbeek** [comment] 2024-11-11 14:46
This Issue seems done to me. Closing it :+1:

**Closed by richelbilderbeek** 2024-11-11 14:46 UTC
